# -*- coding: utf-8 -*-
"""ExportMixin — экспорт SPICE netlist (.cir) из схемы."""

from __future__ import annotations

import re

from PySide6.QtCore import QPointF
from PySide6.QtWidgets import QGraphicsItem

from EDA.core.router import WireItem, WireGraph
from EDA.app.items.component_item import ComponentGraphicsItem
from EDA.app.items.directive_item import DirectiveItem
from EDA.app.items.node_label_item import NetLabelItem


class ExportMixin:
    """Миксин: экспорт схемы в SPICE netlist (.cir) и связанные методы."""

    @staticmethod
    def _auto_fill_model(comp: 'ComponentGraphicsItem'):
        """Заполнить model_line из .lib/.mod файлов по value компонента."""
        _value = comp.value().strip()
        if not _value:
            return
        import re as _re
        from pathlib import Path as _Path
        _lib_dirs = [
            _Path(__file__).resolve().parent.parent.parent.parent / "resources" / "LIB",
            _Path(__file__).resolve().parent.parent.parent.parent / "Mod",
        ]
        for _ld in _lib_dirs:
            if not _ld.exists():
                continue
            for _lf in _ld.rglob("*.lib") if _ld.is_dir() else [_ld]:
                try:
                    _c = _lf.read_text(encoding="utf-8")
                except Exception:
                    continue
                _flat = _re.sub(r'\n\s*\+\s*', ' ', _c)
                for _m in _re.finditer(
                    r'^\s*\.model\s+(\S+)\s+(\S+)\s*(.*)',
                    _flat, _re.MULTILINE | _re.IGNORECASE
                ):
                    if _m.group(1).upper() == _value.upper():
                        comp.set_model_line(f".model {_value} {_m.group(2)} {_m.group(3)}".replace('\n',' ').replace('\r',''))
                        return
                for _m in _re.finditer(
                    r'^\s*\.subckt\s+(\S+)\s*(.*)',
                    _flat, _re.MULTILINE | _re.IGNORECASE
                ):
                    if _m.group(1).upper() == _value.upper():
                        _start = _m.start()
                        _ends = _re.search(r'^\s*\.ends\s+', _c[_start:], _re.MULTILINE | _re.IGNORECASE)
                        if _ends:
                            comp.set_model_line(_c[_start:])
                        else:
                            comp.set_model_line(f".SUBCKT {_value} {_m.group(2)}")
                        return

    # ------------------------------------------------------------------
    # SPICE netlist export (.cir для ngspice)
    # ------------------------------------------------------------------
    def export_cir(self) -> str:
        """Экспорт схемы в SPICE netlist (.cir)."""
        lines = ["* SPICE Netlist generated by EDA Schematic Editor"]
        lines.append(".title Untitled")

        # Шаг 1: сгруппировать провода по связности
        processed: set[WireItem] = set()
        net_groups: list[set[WireItem]] = []
        for item in self._scene.items():
            if not isinstance(item, WireItem):
                continue
            if item in processed:
                continue
            connected = self._wire_graph.get_connected(item)
            processed.update(connected)
            net_groups.append(connected)

        # Шаг 2: проиндексировать все компоненты на сцене
        all_comps: dict[int, ComponentGraphicsItem] = {}
        power_ids: set[int] = set()
        for item in self._scene.items():
            if isinstance(item, ComponentGraphicsItem):
                cid = id(item)
                all_comps[cid] = item
                if "net" in item._data.attributes:
                    power_ids.add(cid)
                elif item._data.attributes.get("device", "").upper() == "GND":
                    power_ids.add(cid)

        # Шаг 3: назначить имена сетям
        net_names: list[str] = []
        net_counter = 0
        for group in net_groups:
            name = None
            for (cid, _pin_idx), (w, _wi, _px, _py) in self._comp_wire_links.items():
                if cid not in power_ids:
                    continue
                if w not in group:
                    continue
                comp = all_comps.get(cid)
                if comp is None:
                    continue
                dev = comp._data.attributes.get("device", "").upper()
                net_attr = comp._data.attributes.get("net", "")
                if net_attr:
                    label = net_attr.split(":")[0] if ":" in net_attr else net_attr
                    if label.upper() == "GND":
                        name = "0"
                    else:
                        name = label
                elif dev == "GND":
                    name = "0"
                break
            # Шаг 3b: проверить метки узлов (NetLabelItem)
            if name is None:
                for item in self._scene.items():
                    if not isinstance(item, NetLabelItem):
                        continue
                    anchor = item.pos()
                    for w in group:
                        pts = w.points()
                        for i in range(len(pts) - 1):
                            a, b = pts[i], pts[i + 1]
                            if abs(a.x() - b.x()) < 0.1:  # Вертикаль
                                if abs(anchor.x() - a.x()) <= 30:
                                    if min(a.y(), b.y()) - 30 <= anchor.y() <= max(a.y(), b.y()) + 30:
                                        name = item.text()
                                        break
                            else:  # Горизонталь
                                if abs(anchor.y() - a.y()) <= 30:
                                    if min(a.x(), b.x()) - 30 <= anchor.x() <= max(a.x(), b.x()) + 30:
                                        name = item.text()
                                        break
                        if name is not None:
                            break
            if name is None:
                net_counter += 1
                name = str(net_counter)
            net_names.append(name)

        # Шаг 4: pin_index → net_name для каждого компонента
        pin_to_net: dict[int, dict[int, str]] = {}
        for (cid, pin_idx), (w, _wi, _px, _py) in self._comp_wire_links.items():
            if cid in power_ids:
                continue
            if cid not in pin_to_net:
                pin_to_net[cid] = {}
            for i, group in enumerate(net_groups):
                if w in group:
                    pin_to_net[cid][pin_idx] = net_names[i]
                    break

        # Шаг 5: сформировать SPICE-строки (компоненты)
        comp_lines: list[str] = []
        dir_lines: list[str] = []
        for cid, pin_nets in pin_to_net.items():
            comp = all_comps.get(cid)
            if comp is None:
                continue
            refdes = comp.refdes() or "U?"
            value = comp.value() or ""
            device = comp._data.attributes.get("device", "").upper()
            pins = comp._data.pins

            line = self._spice_device_line(refdes, device, value, pins, pin_nets,
                                               comp._data.attributes)
            if line:
                comp_lines.append(line)
            else:
                unconn = [str(p.pinnumber) for i, p in enumerate(pins)
                          if i not in pin_nets]
                if unconn:
                    comp_lines.append(
                        f"* {refdes}: device={device} — пины {','.join(unconn)} не подключены")
                else:
                    comp_lines.append(f"* {refdes}: device={device} не поддерживается")

        # Шаг 6: MODEL / DIRECTIVE — не-электрические аннотации, вставляются без привязки к проводам
        for cid, comp in all_comps.items():
            if cid in pin_to_net or cid in power_ids:
                continue
            device = comp._data.attributes.get("device", "").upper()
            if device not in ("MODEL", "DIRECTIVE"):
                continue
            refdes = comp.refdes() or "A?"
            value = comp.value() or ""
            line = self._spice_device_line(refdes, device, value, comp._data.pins, {})
            if line:
                comp_lines.append(line)

        # Шаг 7: DirectiveItem — standalone-тексты директив
        for item in self._scene.items():
            if not isinstance(item, DirectiveItem):
                continue
            text = item.text().strip()
            if text.startswith(".") or text.upper().startswith("IC="):
                dir_lines.append(text)
            else:
                dir_lines.append(f".{text}")

        # Шаг 8: MODEL-директивы из компонентов (уникальные)
        model_lines: list[str] = []
        seen: set[str] = set()
        for item in self._scene.items():
            if not isinstance(item, ComponentGraphicsItem):
                continue
            self._auto_fill_model(item)
            ml = item.model_line()
            if ml and ml not in seen:
                seen.add(ml)
                model_lines.append(ml)
        model_lines.sort()

        # Автоматическая .MODEL swmod для VC-переключателей
        if getattr(self.__class__, '_swmod_needed', False):
            self.__class__._swmod_needed = False
            swmod_line = ".MODEL swmod SW(VT=0.5 VH=0.1 RON=1 ROFF=1G)"
            if swmod_line not in model_lines:
                model_lines.append(swmod_line)

        comp_lines.sort()
        dir_lines.sort(key=lambda t: (1 if t.lstrip().lower().startswith(('.print', '.plot', '.probe')) else 0, t))
        lines.extend(comp_lines)
        lines.extend(model_lines)
        lines.extend(dir_lines)
        lines.append(".end")
        return "\n".join(lines)

    @staticmethod
    def _spice_device_line(refdes: str, device: str, value: str,
                           pins, pin_nets: dict[int, str],
                           attributes: dict | None = None) -> str | None:
        """Сформировать одну строку SPICE для компонента."""

        def pinnumber_index(target: str) -> int | None:
            for i, p in enumerate(pins):
                if p.pinnumber == target:
                    return i
            return None

        def net(idx: int) -> str | None:
            return pin_nets.get(idx)

        # Пассивные 2-выводные (refdes уже содержит префикс R/C/L)
        if device in ("RESISTOR",):
            n0, n1 = net(0), net(1)
            if n0 is None or n1 is None:
                return None
            return f"{refdes} {n0} {n1} {value}" if value else f"{refdes} {n0} {n1}"

        if device in ("CAPACITOR", "POLARIZED_CAPACITOR"):
            n0, n1 = net(0), net(1)
            if n0 is None or n1 is None:
                return None
            return f"{refdes} {n0} {n1} {value}" if value else f"{refdes} {n0} {n1}"

        if device == "INDUCTOR":
            n0, n1 = net(0), net(1)
            if n0 is None or n1 is None:
                return None
            return f"{refdes} {n0} {n1} {value}" if value else f"{refdes} {n0} {n1}"

        # Диоды: pinnumber=1 = anode, pinnumber=2 = cathode
        if device in ("DIODE", "ZENER_DIODE", "LED"):
            na = net(0)
            nc = net(1)
            if na is None or nc is None:
                return None
            model = value if value else device.lower()
            return f"{refdes} {na} {nc} {model}"

        # Источники напряжения / тока
        if device in ("VOLTAGE_SOURCE", "VAC", "VDC"):
            np_pos, np_neg = net(0), net(1)
            if np_pos is None or np_neg is None:
                return None
            val = value if value else "0"
            return f"{refdes} {np_pos} {np_neg} {val}"

        if device == "VSIN":
            np_pos, np_neg = net(0), net(1)
            if np_pos is None or np_neg is None:
                return None
            val = value if value else "SIN(0 1 1k)"
            return f"{refdes} {np_pos} {np_neg} {val}"

        if device == "VPULSE":
            np_pos, np_neg = net(0), net(1)
            if np_pos is None or np_neg is None:
                return None
            val = value if value else "PULSE(0 1 0 1n 1n 50u 100u)"
            return f"{refdes} {np_pos} {np_neg} {val}"

        if device == "VPWL":
            np_pos, np_neg = net(0), net(1)
            if np_pos is None or np_neg is None:
                return None
            val = value if value else "PWL(0 0 1u 1)"
            return f"{refdes} {np_pos} {np_neg} {val}"

        if device == "VEXP":
            np_pos, np_neg = net(0), net(1)
            if np_pos is None or np_neg is None:
                return None
            val = value if value else "EXP(0 1 0 1u 0 1u)"
            return f"{refdes} {np_pos} {np_neg} {val}"

        if device == "CURRENT_SOURCE":
            np_pos, np_neg = net(0), net(1)
            if np_pos is None or np_neg is None:
                return None
            val = value if value else "0"
            return f"{refdes} {np_pos} {np_neg} {val}"

        # Биполярные транзисторы: pinnumber=C, B, E
        if device in ("NPN_TRANSISTOR", "PNP_TRANSISTOR"):
            i_c = pinnumber_index("C")
            i_b = pinnumber_index("B")
            i_e = pinnumber_index("E")
            if i_c is None or i_b is None or i_e is None:
                # fallback: index order
                n0, n1, n2 = net(0), net(1), net(2)
                if n0 is None or n1 is None or n2 is None:
                    return None
                model = value if value else device.lower()
                return f"{refdes} {n0} {n1} {n2} {model}"
            nc = net(i_c)
            nb = net(i_b)
            ne = net(i_e)
            if nc is None or nb is None or ne is None:
                return None
            model = value if value else device.lower()
            return f"{refdes} {nc} {nb} {ne} {model}"

        # Полевые транзисторы: pinnumber=D, G, S
        if device in ("NMOS_TRANSISTOR", "PMOS_TRANSISTOR"):
            i_d = pinnumber_index("D")
            i_g = pinnumber_index("G")
            i_s = pinnumber_index("S")
            if i_d is not None and i_g is not None and i_s is not None:
                nd = net(i_d)
                ng = net(i_g)
                ns = net(i_s)
                if nd is None or ng is None or ns is None:
                    return None
                model = value if value else device.lower()
                return f"{refdes} {nd} {ng} {ns} 0 {model}"
            n0, n1, n2 = net(0), net(1), net(2)
            if n0 is None or n1 is None or n2 is None:
                return None
            model = value if value else device.lower()
            return f"{refdes} {n0} {n1} {n2} 0 {model}"

        # Директивы и модели SPICE
        if device == "DIRECTIVE":
            return value if value else None

        if device == "MODEL":
            return value if value else None

        # Операционные усилители AOP-Standard: pinnumber → SPICE порядок
        if device == "AOP-STANDARD":
            pin_order = ["1", "2", "3", "4", "5"]  # N+ N- V+ V- OUT
            nets = []
            for pn in pin_order:
                idx = pinnumber_index(pn)
                if idx is not None:
                    n = net(idx)
                    if n is None:
                        return None
                    nets.append(n)
                else:
                    return None
            model = value if value else "LM741"
            return f"X{refdes} {' '.join(nets)} {model}"

        # Сложные IC → X (subcircuit call)
        if device in ("OPAMP", "DUAL_OPAMP", "QUAD_OPAMP",
                      "COMPARATOR", "DUAL_COMPARATOR",
                      "LM555",
                      "LM741", "LM358", "LM324", "LM311", "LM393",
                      "LM339", "LM319", "LM2902",
                      "LT1782", "LTC1799", "LTC2400", "LT1761SD",
                      "LT1374CS8", "LT1376", "LP2954IT", "LM2941T",
                      "LM2576T", "LM2822M", "L200"):
            def _pin_sort_key(i):
                pn = pins[i].pinnumber
                if pn and pn.isdigit():
                    return int(pn)
                return i
            sorted_indices = sorted(range(len(pins)), key=_pin_sort_key)
            net_list = [pin_nets.get(i, "NC") for i in sorted_indices]
            if not any(n != "NC" for n in net_list):
                return None
            model = value if value else device.lower()
            return f"X{refdes} {' '.join(net_list)} {model}"

        # Трансформатор: две обмотки + коэффициент связи K
        if device == "TRANSFORMER":
            i_p1 = pinnumber_index("1")
            i_p2 = pinnumber_index("2")
            i_s1 = pinnumber_index("3")
            i_s2 = pinnumber_index("4")
            if None in (i_p1, i_p2, i_s1, i_s2):
                return None
            np1 = net(i_p1)
            np2 = net(i_p2)
            ns1 = net(i_s1)
            ns2 = net(i_s2)
            if None in (np1, np2, ns1, ns2):
                return None
            parts = value.split() if value else ["1m", "1m", "0.99"]
            if len(parts) == 1:
                l_val = parts[0]
                parts = [l_val, l_val, "0.99"]
            l1_val, l2_val, k_val = parts[0], parts[1], parts[2]
            s = f"{refdes}_L1 {np1} {np2} {l1_val}\n{refdes}_L2 {ns1} {ns2} {l2_val}\nK_{refdes} {refdes}_L1 {refdes}_L2 {k_val}"
            return s

        # SPICE voltage-controlled switch: S<refdes> N+ N- NC+ NC- <model>
        if device == "SPICE-VC-SWITCH":
            i_nplus = pinnumber_index("1")
            i_nminus = pinnumber_index("2")
            i_ncplus = pinnumber_index("3")
            i_ncminus = pinnumber_index("4")
            if None in (i_nplus, i_nminus, i_ncplus, i_ncminus):
                return None
            nplus = net(i_nplus)
            nminus = net(i_nminus)
            ncplus = net(i_ncplus)
            ncminus = net(i_ncminus)
            if None in (nplus, nminus, ncplus, ncminus):
                return None
            attrs = attributes or {}
            model = attrs.get("model-name", value) or "swmod"
            from EDA.app.canvas.canvas_core import SchematicCanvas
            SchematicCanvas._swmod_needed = True
            return f"{refdes} {nplus} {nminus} {ncplus} {ncminus} {model}"

        return None
